name: TPM
options:
  bundleIdPrefix: com.vizlab.tpm
  deploymentTarget:
    macOS: "15.0"
    iOS: "17.0"

packages:
  Vapor:
    url: https://github.com/vapor/vapor.git
    from: 4.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 8.0.0

targets:
  TPM:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vizlab.tpm
        INFOPLIST_FILE: SupportingFiles/Info.plist
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        # Optional: if you later turn Sandbox on, you'll need entitlements/bookmarks for /Volumes access.
    dependencies:
      - package: Vapor
        product: Vapor
  TPMiOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vizlab.tpmios
        INFOPLIST_FILE: Sources/iOS/SupportingFiles/Info.plist
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone + iPad
        SUPPORTS_MACCATALYST: "NO"
    dependencies:
      - package: Kingfisher
        product: Kingfisher

schemes:
  TPM:
    build:
      targets:
        TPM: all
    run:
      config: Debug
  TPMiOS:
    build:
      targets:
        TPMiOS: all
    run:
      config: Debug
