/*
 * Copyright (c) Vizlab Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

import SwiftUI

struct ContentView: View {
  var body: some View {
    NavigationStack {
      VStack(spacing: 12) {
        Image(systemName: "sparkles")
          .font(.system(size: 48))
        Text("TPMiOS")
          .font(.title)
          .fontWeight(.semibold)
        Text("SwiftUI app target generated by XcodeGen.")
          .foregroundStyle(.secondary)
      }
      .padding()
      .navigationTitle("Home")
    }
  }
}

#Preview {
  ContentView()
}
